# -*- coding: utf-8 -*-
"""Copy of Aeronautics_Analysis_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yVqKdZDIXmjkottBPpA2gz1N7PuAX2P8

# ✈️ Analyse des opérations aéronautiques — Notebook


### Objectifs
- Charger et préparer les données avec **Pandas**
- Explorer le dataset
- Calculer quelques indicateurs (KPI)
- Visualiser les retards, routes, compagnies et types d'avions
- Étudier les corrélations entre variables
- Visualiser les positions et les flux entre aéroports

## 1. Importation des bibliothèques
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline

# Options d'affichage
pd.set_option("display.max_columns", None)
sns.set_theme(style="whitegrid")

"""## 2. Chargement du fichier CSV

`pandas.read_csv()` permet de lire le fichier CSV et de le transformer en **DataFrame**.

"""

# Le fichier CSV doit être placé dans le même dossier que le notebook.
# Le second chemin permet aussi l'exécution directe dans l'environnement fourni.

try:
    df = pd.read_csv("flights_aero.csv")
except FileNotFoundError:
    df = pd.read_csv("/mnt/data/flights_aero.csv")

# Conversion de la date en vrai format datetime
df["date"] = pd.to_datetime(df["date"], errors="coerce")

print("Dimensions du dataset :", df.shape)
df.head()

"""## 3. Première exploration avec Pandas"""

# Noms des colonnes
df.columns.tolist()

# Informations générales : types de données et valeurs non nulles
df.info()

# Statistiques descriptives des colonnes numériques
df.describe().T

# Valeurs manquantes par colonne
missing = df.isna().sum().sort_values(ascending=False)
missing[missing > 0]

"""## 4. Quelques informations utiles sur les données"""

print("Nombre total de vols :", len(df))
print("Nombre de compagnies :", df["airline"].nunique())
print("Nombre de types d'avions :", df["aircraft_type"].nunique())
print("Nombre d'aéroports de départ :", df["origin"].nunique())
print("Période :", df["date"].min().date(), "→", df["date"].max().date())

# Nombre de vols par compagnie
df["airline"].value_counts()

# Nombre de vols par type d'avion
df["aircraft_type"].value_counts()

"""## 5. Préparation des données"""

# Création d'une colonne route
df["route"] = df["origin"].astype(str) + " → " + df["destination"].astype(str)

# Aperçu
df[["flight_id", "date", "airline", "aircraft_type", "route", "delay_min"]].head()

"""## 6. KPI — Indicateurs principaux"""

kpis = pd.Series({
    "Nombre de vols": len(df),
    "Retard moyen (min)": df["delay_min"].mean(),
    "Consommation moyenne (kg)": df["fuel_burn_kg"].mean(),
    "CO₂ total (kg)": df["co2_kg"].sum(),
    "Load factor moyen": df["load_factor"].mean(),
    "Nombre moyen de passagers": df["passengers"].mean()
})

kpis

"""## 7. Analyse temporelle des retards — Matplotlib

On calcule d'abord le **retard moyen par jour**, puis on trace son évolution.

"""

daily_delay = (
    df.groupby("date", as_index=False)["delay_min"]
      .mean()
      .sort_values("date")
)

plt.figure(figsize=(14, 5))
plt.plot(daily_delay["date"], daily_delay["delay_min"])
plt.xlabel("Date")
plt.ylabel("Retard moyen (min)")
plt.title("Évolution du retard moyen par jour")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## 8. Top 10 des routes — Seaborn"""

route_counts = (
    df["route"]
    .value_counts()
    .head(10)
    .rename_axis("route")
    .reset_index(name="count")
)

route_counts

plt.figure(figsize=(10, 6))
sns.barplot(data=route_counts, x="count", y="route", color="#4C72B0")
plt.xlabel("Nombre de vols")
plt.ylabel("Route")
plt.title("Top 10 des routes par nombre de vols")
plt.tight_layout()
plt.show()

"""## 9. Distribution des retards par compagnie — Boxplot"""

top_airlines = df["airline"].value_counts().head(10).index
box_df = df[df["airline"].isin(top_airlines)]

plt.figure(figsize=(11, 6))
sns.boxplot(data=box_df, x="delay_min", y="airline", color="#4C72B0")
plt.xlabel("Retard (min)")
plt.ylabel("Compagnie")
plt.title("Distribution des retards par compagnie")
plt.tight_layout()
plt.show()

"""## 10. Matrice de corrélation — Seaborn"""

num_cols = [
    "distance_km",
    "duration_min",
    "delay_min",
    "cruise_altitude_ft",
    "cruise_speed_kts",
    "fuel_burn_kg",
    "co2_kg",
    "load_factor",
    "passengers"
]

corr = df[num_cols].corr()

plt.figure(figsize=(11, 8))
sns.heatmap(corr, annot=True, fmt=".2f")
plt.title("Matrice de corrélation")
plt.tight_layout()
plt.show()

"""## 11. Retard moyen par compagnie — Matplotlib"""

avg_delay_airline = (
    df.groupby("airline", as_index=False)["delay_min"]
      .mean()
      .sort_values("delay_min", ascending=False)
)

avg_delay_airline

plt.figure(figsize=(11, 5))
plt.bar(avg_delay_airline["airline"], avg_delay_airline["delay_min"])
plt.xlabel("Compagnie")
plt.ylabel("Retard moyen (min)")
plt.title("Retard moyen par compagnie")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

"""## 12. Répartition des vols par type d'avion — Camembert"""

aircraft_counts = df["aircraft_type"].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(
    aircraft_counts.values,
    labels=aircraft_counts.index,
    autopct="%1.1f%%",
    startangle=90
)
plt.title("Répartition des vols par type d'avion")
plt.axis("equal")
plt.show()

"""## 13. Distribution générale des retards"""

plt.figure(figsize=(10, 5))
sns.histplot(df["delay_min"], bins=30, kde=True, color="#4C72B0")
plt.xlabel("Retard (min)")
plt.ylabel("Nombre de vols")
plt.title("Distribution des retards")
plt.tight_layout()
plt.show()

"""## 14. Distance et consommation de carburant"""

plt.figure(figsize=(9, 6))
sns.scatterplot(
    data=df,
    x="distance_km",
    y="fuel_burn_kg",
    hue="airline",
    alpha=0.75
)
plt.xlabel("Distance (km)")
plt.ylabel("Carburant consommé (kg)")
plt.title("Relation entre distance et consommation de carburant")
plt.tight_layout()
plt.show()

"""## 15. Distance et émissions de CO₂"""

plt.figure(figsize=(9, 6))
sns.scatterplot(
    data=df,
    x="distance_km",
    y="co2_kg",
    hue="aircraft_type",
    alpha=0.75
)
plt.xlabel("Distance (km)")
plt.ylabel("CO₂ (kg)")
plt.title("Relation entre distance et émissions de CO₂")
plt.tight_layout()
plt.show()

"""## 16. Positions des vols — remplacement de `st.map`

Dans l'application Streamlit, les coordonnées étaient affichées avec `st.map`.  
Dans le notebook, on utilise un **scatter plot Matplotlib**.

"""

positions = df[["lat", "lon"]].dropna()

plt.figure(figsize=(10, 7))
plt.scatter(positions["lon"], positions["lat"], alpha=0.5)
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("Positions géographiques des vols")
plt.grid(True)
plt.tight_layout()
plt.show()

"""## 17. Flux origine → destination — Matplotlib

La visualisation PyDeck de l'application est remplacée par une figure Matplotlib simple reliant les aéroports connus.

"""

airport_coords = {
    "CMN": (33.3675, -7.5897),
    "RAK": (31.6069, -8.0363),
    "TNG": (35.7269, -5.9169),
    "AGA": (30.3250, -9.4131),
    "ORY": (48.7233, 2.3794),
    "MAD": (40.4722, -3.5608),
    "LHR": (51.4700, -0.4543),
    "IST": (41.2603, 28.7420),
}

route_flows = (
    df.groupby(["origin", "destination"])
      .size()
      .reset_index(name="count")
      .sort_values("count", ascending=False)
)

route_flows.head(10)

plt.figure(figsize=(12, 8))

# Affichage des aéroports
for code, (lat, lon) in airport_coords.items():
    plt.scatter(lon, lat, s=70)
    plt.text(lon + 0.3, lat + 0.3, code, fontsize=10)

# Affichage des flux
for _, row in route_flows.iterrows():
    origin = airport_coords.get(row["origin"])
    destination = airport_coords.get(row["destination"])

    if origin and destination:
        o_lat, o_lon = origin
        d_lat, d_lon = destination

        # largeur légèrement proportionnelle au nombre de vols
        width = 0.5 + row["count"] / route_flows["count"].max() * 3

        plt.plot(
            [o_lon, d_lon],
            [o_lat, d_lat],
            linewidth=width,
            alpha=0.45
        )

plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("Flux entre les principaux aéroports")
plt.grid(True)
plt.tight_layout()
plt.show()

"""## 18. Exemple de filtrage avec Pandas"""

# Exemple : filtrer une compagnie
compagnie = df["airline"].dropna().iloc[0]

df_filtre = df[df["airline"] == compagnie]

print("Compagnie sélectionnée :", compagnie)
print("Nombre de vols :", len(df_filtre))

df_filtre.head()

# Exemple : filtrer par période
date_debut = df["date"].min()
date_fin = date_debut + pd.Timedelta(days=30)

df_periode = df[df["date"].between(date_debut, date_fin)]

print("Période :", date_debut.date(), "→", date_fin.date())
print("Nombre de vols :", len(df_periode))

df_periode.head()

"""## 19. Tableau final des données

On peut afficher le DataFrame final directement dans le notebook.

"""

df.head(20)